language: node_js

services:
  - docker

before_install:
  - docker build -t gaspatelemetry_monitor .

script:
  - docker run -d -p 127.0.0.1:80:3000 telemetry_monitor:latest 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
