version: '3.0'

services:
  telemetry_monitor:
    build:
      context: .
      dockerfile: Dockerfile
    image: telemetry_monitor:latest
    restart: unless-stopped 
    ports:
      - "3000:3000"
